In [3]:
import pandas as pd

In [4]:
df_v=pd.read_csv("countries_vente_N.csv",encoding="Latin 1")

In [7]:
df_ar=df_v[df_v["Country"]=="Ariana"]

In [12]:
def price_size(a, b):
    return a / b

In [15]:
df_v['Moy_PS'] = df_v.apply(lambda row: price_size(row['Price'], row['Size']), axis=1)

In [19]:
650000.0/157

4140.127388535032

In [20]:
df_v.head()

         Country     Price  Size    Status Marketplace       Moy_PS
0         Ariana  180000.0    68  A vendre    Jumia TN  2647.058824
1         Nabeul  650000.0   157  A vendre    Jumia TN  4140.127389
2      Ben arous  252000.0   180  A vendre    Jumia TN  1400.000000
3         Nabeul  170000.0   180  A vendre    Jumia TN   944.444444
4  Banlieue Nord  350000.0   140  A vendre    Jumia TN  2500.000000

In [39]:
df_biz=df_v[df_v["Country"]=="Bizerte"]

In [48]:
df_biz

     Country      Price  Size    Status Marketplace        Moy_PS
111  Bizerte   230000.0   121  A vendre    Jumia TN  1.900826e+03
260  Bizerte   185000.0   150  A vendre    Jumia TN  1.233333e+03
426  Bizerte   350000.0   200  A vendre    Jumia TN  1.750000e+03
506  Bizerte   200000.0   130  A vendre    Jumia TN  1.538462e+03
551  Bizerte   120000.0    90  A vendre    Jumia TN  1.333333e+03
602  Bizerte   115000.0    90  A vendre    Jumia TN  1.277778e+03
688  Bizerte  1300000.0     1  A vendre    Jumia TN  1.300000e+06
698  Bizerte   210000.0    60  A vendre    Jumia TN  3.500000e+03

In [55]:
df_biz["Price"][698]/df_biz["Size"][698]

3500.0

In [73]:
df_ar=df_v[df_v["Country"]=="Bizerte"]

In [76]:
df_ar["Moy_PS"].sum()/8

164066.71655364838

In [77]:
df_v

           Country      Price  Size    Status Marketplace        Moy_PS
0           Ariana   180000.0    68  A vendre    Jumia TN  2.647059e+03
1           Nabeul   650000.0   157  A vendre    Jumia TN  4.140127e+03
2        Ben arous   252000.0   180  A vendre    Jumia TN  1.400000e+03
3           Nabeul   170000.0   180  A vendre    Jumia TN  9.444444e+02
4    Banlieue Nord   350000.0   140  A vendre    Jumia TN  2.500000e+03
5           Sousse   800000.0   150  A vendre    Jumia TN  5.333333e+03
6           Ariana   210000.0   157  A vendre    Jumia TN  1.337580e+03
7           Ariana   543904.0   236  A vendre    Jumia TN  2.304678e+03
8           Ariana   160000.0   150  A vendre    Jumia TN  1.066667e+03
9        Ben arous   188000.0   106  A vendre    Jumia TN  1.773585e+03
10          Nabeul   345000.0   142  A vendre    Jumia TN  2.429577e+03
11          Sousse      950.0   160  A vendre    Jumia TN  5.937500e+00
12   Banlieue Nord   650000.0     1  A vendre    Jumia TN  6.500000e+05
13   Banlieue Nord   410000.0   165  A vendre    Jumia TN  2.484848e+03
14          Ariana   214550.0   123  A vendre    Jumia TN  1.744309e+03
15          Ariana   175000.0    75  A vendre    Jumia TN  2.333333e+03
16       Ben arous   160000.0   129  A vendre    Jumia TN  1.240310e+03
17          Sousse   270000.0    63  A vendre    Jumia TN  4.285714e+03
18       Ben arous   145000.0   100  A vendre    Jumia TN  1.450000e+03
19       Ben arous    80000.0    80  A vendre    Jumia TN  1.000000e+03
20   Banlieue Nord   235000.0   135  A vendre    Jumia TN  1.740741e+03
21   Banlieue Nord   450000.0   152  A vendre    Jumia TN  2.960526e+03
22   Banlieue Nord   950000.0     1  A vendre    Jumia TN  9.500000e+05
23   Banlieue Nord  1500000.0     1  A vendre    Jumia TN  1.500000e+06
24          Ariana   258000.0    99  A vendre    Jumia TN  2.606061e+03
25   Banlieue Nord  1500000.0   280  A vendre    Jumia TN  5.357143e+03
26          Ariana   257000.0   136  A vendre    Jumia TN  1.889706e+03
27          Nabeul   235000.0     1  A vendre    Jumia TN  2.350000e+05
28   Banlieue Nord   640000.0     1  A vendre    Jumia TN  6.400000e+05
29          Ariana   160000.0   150  A vendre    Jumia TN  1.066667e+03
..             ...        ...   ...       ...         ...           ...
943         Sousse   138000.0    40  A vendre    Jumia TN  3.450000e+03
944         Nabeul   225000.0    94  A vendre    Jumia TN  2.393617e+03
945         Ariana   365000.0   163  A vendre    Jumia TN  2.239264e+03
946         Ariana   498000.0   172  A vendre    Jumia TN  2.895349e+03
947  Banlieue Nord   304900.0   128  A vendre    Jumia TN  2.382031e+03
948  Banlieue Nord   170000.0    89  A vendre    Jumia TN  1.910112e+03
949         Ariana   490000.0   178  A vendre    Jumia TN  2.752809e+03
950  Banlieue Nord   390000.0   204  A vendre    Jumia TN  1.911765e+03
951  Banlieue Nord   450000.0   150  A vendre    Jumia TN  3.000000e+03
952  Banlieue Nord   457800.0   120  A vendre    Jumia TN  3.815000e+03
953  Banlieue Nord   200000.0    63  A vendre    Jumia TN  3.174603e+03
954  Banlieue Nord   263000.0    89  A vendre    Jumia TN  2.955056e+03
955         Ariana   450000.0   238  A vendre    Jumia TN  1.890756e+03
956  Banlieue Nord   395000.0   150  A vendre    Jumia TN  2.633333e+03
957  Banlieue Nord   343565.0    94  A vendre    Jumia TN  3.654947e+03
958         Sousse   300000.0   148  A vendre    Jumia TN  2.027027e+03
959         Nabeul   260000.0    81  A vendre    Jumia TN  3.209877e+03
960           Sfax   112000.0    94  A vendre    Jumia TN  1.191489e+03
961           Sfax   150000.0   134  A vendre    Jumia TN  1.119403e+03
962      Ben arous   130000.0    70  A vendre    Jumia TN  1.857143e+03
963  Banlieue Nord   400000.0   152  A vendre    Jumia TN  2.631579e+03
964  Banlieue Nord   390000.0   176  A vendre    Jumia TN  2.215909e+03
965  Banlieue Nord   800000.0   636  A vendre    Jumia TN  1.257862e+03
966  Banlieue Nord   430000.0     1  A vendre    Jumia TN  4.300000e+05
967  Banlieue Nord   491000.0   217  A vendre    Jumia TN  2.262673e+03
968  Banlieue Nord   185000.0    92  A vendre    Jumia TN  2.010870e+03
969         Ariana   700000.0   254  A vendre    Jumia TN  2.755906e+03
970         Nabeul   180000.0   110  A vendre    Jumia TN  1.636364e+03
971  Banlieue Nord   645000.0     1  A vendre    Jumia TN  6.450000e+05
972  Banlieue Nord   436000.0   120  A vendre    Jumia TN  3.633333e+03

[973 rows x 6 columns]

In [78]:
df_v.to_csv("countries_vente_N.csv",index=False)

In [79]:
df_loc=pd.read_csv("countries_loc_N.csv",encoding="Latin 1")

In [80]:
df_loc['Moy_PS'] = df_loc.apply(lambda row: price_size(row['Price'], row['Size']), axis=1)

In [81]:
df_loc.to_csv("countries_loc_N.csv",index=False)